### ISSUE TITLE
Possible features

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PredictPokemon-1#2]
- Density of population --> Hypotesis: The more people living in an area, the more pokemon
- 3G quality/coverage
- Sales of smartphones in a certain area/country

**Comment by goldbergtatyana** [comment]
You will need to work tightly with the group of Project A (PokeData) to decide upon which features could be useful for the prediction. @marwage @MatthiasBaur what are your ideas so far for the features?

**Comment by sacdallago** [comment]
Well but for these features they can do some data collection in their own ;)

**Comment by goldbergtatyana** [comment]
Yes sure on their own for now! :)

**Comment by marwage** [comment]
- location
- landscape
- is a pokestop nearby (lure module)
- level of trainer
- number of pokemon players (in city or country)

density of population sounds very good

**Comment by goldbergtatyana** [comment]
this is good! what about the sources for each of them?

**Comment by goldbergtatyana** [comment]
Hi @marwage @MatthiasBaur @TimKhodzhaev ! Where are you guys standing right now with the project? Is all clear so far?
