### ISSUE TITLE
Map names

### ISSUE THREAD

**Issue by marwage** [PokemonGoers/PredictPokemon-1#3]
I worked with the Node.js package **node-svm**
and I think it only takes **numbers** as input.
So we have to map for example a pokemon name to a id and backwards
to use that package.
(Or I didn't find how it takes strings)

**Comment by sacdallago** [comment]
There's already a mapping from pokemon to id https://github.com/PokemonGoers/PokeData/blob/develop/resources/json/pokemonIdAndName.json
