### ISSUE TITLE
node-svm always same prediction

### ISSUE THREAD

**Issue by marwage** [PokemonGoers/PredictPokemon-1#4]
I read in `dummy1.json`
and trained it with `node-svm`
the result for all latitudes and longitudes is 16.
Is it only possible to use -1,+1
or can I use more?
or would naive bayes better? @goldbergtatyana

**Comment by goldbergtatyana** [comment]
Thats great @marwage that you tried node-svm and that you got a result. Though result is meaningless 😆 

Please upload your arff file here on Github and describe what steps you performed with WEKA (there is an SVM algorithm implemented as well). I am most familiar with Weka and can surely provide you help. Also, it would be interesting to see if we can achieve better prediction results with other classification algorithms that SVM, which are also implemented in Weka. :)
