### ISSUE TITLE
node-svm classifier

### ISSUE THREAD

**Issue by marwage** [PokemonGoers/PredictPokemon-1#5]
@goldbergtatyana Can you say a little bit more about the different classifier
and wich one we should use?

**Comment by marwage** [comment]
Ok.
WEKA first.

**Comment by sacdallago** [comment]
@marwage there are a number ([A LOT](https://jixta.files.wordpress.com/2015/11/machinelearningalgorithms.png)) of different classifiers out there! Most of the time it depends on what problem you try to solve and what input data you have, but I have recently heard from a big company that at the end of the day you can use whatever you want as long as it produces the best results :)

A simple google search results in: http://machinelearningmastery.com/a-tour-of-machine-learning-algorithms/

As @goldbergtatyana suggested, it's best that you try out with WEKA which classifier produces the best results :)

**Comment by goldbergtatyana** [comment]
Hi ML Team,

Please upload your arff file here and your ideas about how you *would* use weka for making predictions of pokemon appearances. To begin, we can develop a model for only one single Pokemon - what would be your positive (Pokemon appears) and what would be your negative (Pokemon does not appear) data sets? Once we have these data sets, how would you test the prediction accuracy of the model?

No worries if answers to these questions are not obvious! We are here to teach/learn ;)
